### PR TITLE
Fix timestamp when querying zkevm_getBatchByNumer and the batch is only in trusted state

### PR DESCRIPTION
**Pull request by agnusmor**
### What does this PR do?

When querying zkevm_getBatchByNumber endpoint and the batch requested was only in trusted state (not sequenced/virtualized) the timestamp returned in the response for the batch was wrong. The function assigned a "nil" value for the timestamp and this was intrepreted as a very high timestamp value in the json response (future timestamp).

Now the issue is fixed and in the case the batch is only in trusted state it returns the timestamp of the last L2 block in the batch.

### Reviewers

Main reviewers:

@ToniRamirezM 
@tclemos 
@ARR552

### CODE REVIEW

**Comment by ARR552** [comment]
What would happened if the batch is already virtualized?? In this case if you use the timestamp of the last l2 block in the batch the value would be lower than the virtualization time

**Review by ARR552 — APPROVED** [review]
LGTM

**Review by ARR552 — APPROVED** [review]

**Review by Booss13 — COMMENTED** [review]
[]()

**Comment by Booss13** [comment]
> ### What does this PR do?
> 
> 
> 
> When querying zkevm_getBatchByNumber endpoint and the batch requested was only in trusted state (not sequenced/virtualized) the timestamp returned in the response for the batch was wrong. The function assigned a "nil" value for the timestamp and this was intrepreted as a very high timestamp value in the json response (future timestamp).
> 
> 
> 
> Now the issue is fixed and in the case the batch is only in trusted state it returns the timestamp of the last L2 block in the batch.
> 
> 
> 
> ### Reviewers
> 
> 
> 
> Main reviewers:
> 
> 
> 
> @ToniRamirezM 
> 
> @tclemos 
> 
> @ARR552

**Pull request merged**
