### PR TITLE
Improve container startup order in docker-compose

### LINKED ISSUE #1590: Container dependencies
### Description
Currently running docker-compose up with the main docker-compose.yml file causes `zkevm-rpc` and `zkevm-rpc` to exit with an error, because they are unable to connect to the corresponding databases

### Steps to reproduce
1. In a freshly cloned repo run `docker-compose up`

### Additional context
```2023-01-26T09:04:07.172Z        FATAL   cmd/run.go:162  failed to connect to `host=zkevm-state-db user=state_user database=state_db`: dial error (dial tcp 192.168.96.4:5432: connect: connection refused)
/src/log/log.go:140 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:221 github.com/0xPolygonHermez/zkevm-node/log.Fatal()
/src/cmd/run.go:162 main.runMigrations()
/src/cmd/run.go:144 main.runStateMigrations()
/src/cmd/run.go:55 main.start()
/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/command.go:271 github.com/urfave/cli/v2.(*Command).Run()
/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/command.go:264 github.com/urfave/cli/v2.(*Command).Run()
/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/app.go:333 github.com/urfave/cli/v2.(*App).RunContext()
/go/pkg/mod/github.com/urfave/cli/v2@v2.24.1/app.go:310 github.com/urfave/cli/v2.(*App).Run()
/src/cmd/main.go:140 main.main()
/usr/local/go/src/runtime/proc.go:255 runtime.main()
        {"pid": 1, "version": "v0.0.1-RC1-51-g826231e"}```

### PR DESCRIPTION
**Pull request by isavov**
Closes #1590

### What does this PR do?

It updates the main docker-compose.yaml to add health checks for the postgres databases and define the startup order of the containers, so that `docker-compose up` works properly

### Reviewers

Main reviewers:

- @tclemos

Codeowner reviewers:

### CODE REVIEW

**Comment by arnaubennassar** [comment]
please sign the CLA agreement

**Comment by isavov** [comment]
I'm signing the CLA https://github.com/0xPolygonHermez/clabot-config/pull/20

**Review by arnaubennassar — APPROVED** [review]

**Pull request merged**
