### PR TITLE
#2420 sync halt sanity check

### LINKED ISSUE #2420: Halt synchronizer if the state root synced through the trusted state differs from the calculated state root

### PR DESCRIPTION
**Pull request by ARR552**
Closes #2420 

### What does this PR do?

Adds a sanity check for the stateRoots. If the check is not satisfied, the synchronizer halts

### Reviewers

- @agnusmor 
- @ToniRamirezM

### CODE REVIEW

**Review by ToniRamirezM — APPROVED** [review]

**Review by agnusmor — APPROVED** [review]

**Comment by dubuqingfeng** [comment]
After node upgrade, this stop is often encountered

logs：

zkevm-sync        | 2023-09-08T04:01:11.240Z	ERROR	synchronizer/synchronizer.go:1674	fatal error: stateRoot calculated (0xa4df9ab307f8d4f515f2beb9b53a269e1b35aa12252f04ff7af8e33e4c84c293) is different from the stateRoot (0x420661a3c44dc3eb25d9fc7320c80cb4c0d726f97811a99f9f2069347798a2c0) received during the trustedState synchronization 

@ARR552

**Comment by agnusmor** [comment]
Hi, yes, we are aware, we are investigating this. If you restart the synchronizer this should fix the problem.

Thanks to report it!

**Comment by icculp** [comment]
I'm having the same issue on 2/3 of my nodes (us is okay, eu and as halting). I even rsynced from a good node in the us to one that was halting in eu and then the eu node still halted again, identical configs. restarting after it gets stuck does get it moving forward again though

**Comment by agnusmor** [comment]
Can you share the logs with the error you  are getting?

**Comment by icculp** [comment]
The stateroot hash changes each time, restarting moves it along again

```2023-09-11T05:47:35.279Z        ERROR   synchronizer/synchronizer.go:1674       fatal error: stateRoot calculated (0xe01079b3ea0898c66275e8343ad674977a428665e810dd1552742e7401999058) is different from the stateRoot (0x6564cedbb5dd824da7eea95f3ff452636aaaec9e0c1452ed38bfa95d59db1beb) received during the trustedState synchronization 
/src/log/log.go:140 github.com/0xPolygonHermez/zkevm-node/log.appendStackTraceMaybeArgs()
/src/log/log.go:249 github.com/0xPolygonHermez/zkevm-node/log.Errorf()
/src/synchronizer/synchronizer.go:1674 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).halt()
/src/synchronizer/synchronizer.go:1404 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processTrustedBatch()
/src/synchronizer/synchronizer.go:420 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncTrustedState()
/src/synchronizer/synchronizer.go:252 github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync()
/src/cmd/run.go:305 main.runSynchronizer()
        {"pid": 1, "version": "v0.3.0"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).halt
        /src/synchronizer/synchronizer.go:1674
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processTrustedBatch
        /src/synchronizer/synchronizer.go:1404
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncTrustedState
        /src/synchronizer/synchronizer.go:420
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
        /src/synchronizer/synchronizer.go:252
main.runSynchronizer
        /src/cmd/run.go:305```

**Comment by agnusmor** [comment]
@icculp @dubuqingfeng can you share the logs just before you got the error: "zkevm-sync | 2023-09-08T04:01:11.240Z ERROR synchronizer/synchronizer.go:1674 fatal error:"? it will useful if you can share all the logs of the previous 10 min before this error

**Pull request merged**
