### PR TITLE
config: regroup mutual field related to sequencer

### LINKED ISSUE #2016: Synchronizer.TrustedSequencerURL and RPC.SequencerNodeURI should be the same config
# Rationale

Those values represent the exact same thing, it's so it should be a single parameter

# Implementation

Do you have ideas regarding the implementation of this feature?

Create a TrustedSequencer top level config struct that includes:

- TrustedSequencerURL
- IsTrustedSequencer (this already exists but it's floating in the top level without being part of any struct)

Are you willing to implement this feature?

### PR DESCRIPTION
**Pull request by najeal**
Closes #2016 .

### What does this PR do?

Regroup mutual field related to sequencer

### Reviewers

Main reviewers:

- @ARR552 
- @ToniRamirezM 

Codeowner reviewers:

### CODE REVIEW

**Comment by ToniRamirezM** [comment]
Hello @najeal,

Sorry for taking so much time, but we had issues related to the cla signing.

Could you update the PR to solve the conflicts?

Thank you.

**Comment by najeal** [comment]
@ToniRamirezM don’t worry
By the way end2end tests are failing and I have no way to run them locally even those passing the CI.
It looks like zkprover stops running, my machine always ends with a context timeout when trying to contact the executor.

I made a
make build-docker
make compile-scs
make e2e…..-group1

do I miss something?

**Comment by ToniRamirezM** [comment]
It should be enough. Are you running this on a Linux or macOS machine?

**Comment by najeal** [comment]
@ToniRamirezM on macOS

**Comment by ToniRamirezM** [comment]
Ok, the zkProver won't work on macOS.  I understand your computer has a M1 or M2 processor, which are not supported. zkProver uses opcodes not implemented in Rosetta 2.

That's why you get a timeout.

**Comment by ToniRamirezM** [comment]
I am closing this PR as it has ran very out of synch.

**Pull request closed without merging**
