### PR TITLE
Fix criadoperez

### PR DESCRIPTION
**Pull request by criadoperez**
Fixed typos

### CODE REVIEW

**Comment by criadoperez** [comment]
hi! Any update from a reviewer? Thanks!

**Comment by tclemos** [comment]
@criadoperez thanks for the help with the revision.

could you please remove the changes for the `executor.pb.go` file and fix the conflict?
This file is generated automatically in another repo and imported to our repo, and will keep causing conflicts in future versions.

**Comment by criadoperez** [comment]
@tclemos, done. Removed changes on file `executor.pb.go`.

**Review by tclemos — APPROVED** [review]

**Comment by tclemos** [comment]
the json schema test have failed, could you please run the `make config-doc-gen` and commit the changes?

**Comment by criadoperez** [comment]
Sure thing @tclemos, but `make config-doc-gen` isn't in the list of possible `make` commands.
Could you please provide help on how to fix this?

```
~/zkevm-node  fix-criadoperez =  make config-doc-gen                                                                              
make: *** No rule to make target 'config-doc-gen'.  Stop.

 ~/zkevm-node  fix-criadoperez =  make help                                                                                      
build                          Builds the binary locally into ./dist
build-docker                   Builds a docker image with the node binary
build-docker-nc                Builds a docker image with the node binary - but without build cache
generate-code-from-proto       Generates code from proto files
help                           Prints this help
install-git-hooks              Moves hook files to the .git/hooks directory
install-linter                 Installs the linter
lint                           Runs the linter
run-rpc                        Runs all the services need to run a local zkEMV RPC node
stop                           Stops all services
update-external-dependencies   Updates external dependencies like images, test vectors or proto files
 ~/zkevm-node  fix-criadoperez =         
```

**Comment by tclemos** [comment]
Probably when you forked the repo, the `json scheme` feature was not implemented yet.
You must update your repo with the latest changes in our develop branch.

Here is a doc to help you sync the repos between the source and fork
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by criadoperez** [comment]
Thanks for clearing that out for me.  The `json shema test` isn't failing anymore.

**Pull request merged**
