### PR TITLE
chore:fix typos in *.proto && re-generate type file

### PR DESCRIPTION
**Pull request by AdventureSeeker987**
### What does this PR do?
Walk through this code,found some typos.
this PR mainly related to the proto and the generation of file changes, doc-related changes can probably be in another PR.

1.fix typos in *.proto
2. re-generate  type file 

```shell
zkevm-node git:(develop) ✗ make generate-code-from-proto
cd proto/src/proto/hashdb/v1 && protoc --proto_path=. --proto_path=../../../../include --go_out=../../../../../merkletree/hashdb --go-grpc_out=../../../../../merkletree/hashdb --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative hashdb.proto
cd proto/src/proto/executor/v1 && protoc --proto_path=. --go_out=../../../../../state/runtime/executor --go-grpc_out=../../../../../state/runtime/executor --go-grpc_opt=paths=source_relative --go_opt=paths=source_relative executor.proto
cd proto/src/proto/aggregator/v1 && protoc --proto_path=. --proto_path=../../../../include --go_out=../../../../../aggregator/prover --go-grpc_out=../../../../../aggregator/prover --go-grpc_opt=paths=source_relative --go_opt=paths=source_relative aggregator.proto
```

### Reviewers

Main reviewers:

- @John
- @Doe

Codeowner reviewers:

- @-Alice
- @-Bob

### CODE REVIEW

**Comment by AdventureSeeker987** [comment]
> We require contributors/corporates @AdventureSeeker987 to read our Contributor License Agreement, please check the [Individual CLA document](https://github.com/0xPolygonHermez/clabot-config/blob/master/Individual%20CLA%20-%20Polygon%20zkEVM.pdf?rgh-link-date=2023-12-22T08%3A32%3A23Z)/[Corporate CLA document](https://github.com/0xPolygonHermez/clabot-config/blob/master/Corporate%20CLA%20-%20Polygon%20zkEVM.pdf?rgh-link-date=2023-12-22T08%3A32%3A23Z)

Done

**Comment by ToniRamirezM** [comment]
Hi, thanks for contributing.

There is an issue here and is that we maintain the proto files in another repo:

https://github.com/0xPolygonHermez/zkevm-comms-protocol

Also, we are currently working on the Etrog fork ID and so the files are quite "live" and get modifications quite often.

The branch we are working on is feature/fork-etrog

Maybe you could replicate your modifications there:

https://github.com/0xPolygonHermez/zkevm-comms-protocol/tree/feature/fork-etrog/proto

Thanks.

**Comment by AdventureSeeker987** [comment]
> Hi, thanks for contributing.
> 
> There is an issue here and is that we maintain the proto files in another repo:
> 
> [0xPolygonHermez/zkevm-comms-protocol](https://github.com/0xPolygonHermez/zkevm-comms-protocol)
> 
> Also, we are currently working on the Etrog fork ID and so the files are quite "live" and get modifications quite often.
> 
> The branch we are working on is feature/fork-etrog
> 
> Maybe you could replicate your modifications there:
> 
> [0xPolygonHermez/zkevm-comms-protocol@`feature`/fork-etrog/proto](https://github.com/0xPolygonHermez/zkevm-comms-protocol/tree/feature/fork-etrog/proto?rgh-link-date=2023-12-22T08%3A37%3A36Z)
> 
> Thanks.

thks

**Comment by AdventureSeeker987** [comment]
I will close this PR && replicate your modifications here:
[0xPolygonHermez/zkevm-comms-protocol@feature/fork-etrog/proto](https://github.com/0xPolygonHermez/zkevm-comms-protocol/tree/feature/fork-etrog/proto?rgh-link-date=2023-12-22T08%3A37%3A36Z)

**Comment by AdventureSeeker987** [comment]
> I will close this PR && replicate your modifications here: [0xPolygonHermez/zkevm-comms-protocol@feature/fork-etrog/proto](https://github.com/0xPolygonHermez/zkevm-comms-protocol/tree/feature/fork-etrog/proto?rgh-link-date=2023-12-22T08%3A44%3A05Z)

https://github.com/0xPolygonHermez/zkevm-comms-protocol/pull/101

**Pull request closed without merging**
