### PR TITLE
Fix: typos

### PR DESCRIPTION
**Pull request by omahs**
Fix: typos

### CODE REVIEW

**Comment by omahs** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by arnaubennassar** [comment]
Hey @omahs thanks for your contribution! @KonradIT is working on a heavy update on this documentation that may invalidate your PR... Let's wait for #1347 to be merged first.

**Comment by omahs** [comment]
@arnaubennassar ok, no prob! You can mention me after and I'll have a look :)

**Comment by KonradIT** [comment]
Hm @arnaubennassar this PR can be merged now.

**Comment by arnaubennassar** [comment]
@omahs looks like the CLA document is not signed correctly

**Comment by omahs** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by omahs** [comment]
@arnaubennassar I wrote the comment "I have read the CLA Document and I hereby sign the CLA." is there another way to sign the CLA?

**Comment by arnaubennassar** [comment]
@cla-bot check

**Comment by arnaubennassar** [comment]
@cla-bot check

**Review by KonradIT — APPROVED** [review]

**Pull request merged**
