### PR TITLE
Change %w for %v in formated logs

### LINKED ISSUE #1518: Review logs to use `%v` and `%w` correctly
When we log errors using `%w` but the error is actually not wrapped to contain the trace, the error message is actually not logged. A pattern that we could use is to:

- Always log the error with `%v` at the deepest point in the stack (when it's generated), and wrap it here
- Log again in the highest point in the stack using `%w`

### PR DESCRIPTION
**Pull request by arnaubennassar**
Closes #1518

### CODE REVIEW

**Comment by C001-developer** [comment]
could you explain why change the format %w to %v?

**Review by tclemos — CHANGES_REQUESTED** [review]
As I've mentioned in the issue: 
- we must always return errors with `%w`
- we must never log errors with `%w`

Please, review the `returned errors` to keep the `%w` instead of removing it, and please keep the changes to all the `logs`

**Comment by tclemos** [comment]
> could you explain why change the format %w to %v?

The explanation is in the issue when an error is logged with a `%w` instead of the `%v`, the error message is not logged properly.

**Comment by C001-developer** [comment]
> > could you explain why change the format %w to %v?
> 
> The explanation is in this issue #1518, when an error is logged with a `%w` instead of the `%v`, the error message is not logged properly.

Can you share the detail example of it? 
Because , AFAIK, %w will return the wrapped one if error implement Wrap, in the other case %w is same with %v.

For me, the reason of log not working properly is due to the wrong implementation of Wrap function

**Pull request closed without merging**
