### PR TITLE
Update on documentation for running a local node

### PR DESCRIPTION
**Pull request by kmurphypolygon**
- This PR removes the docs for spinning up a node and adds a link to the live documentation site where it now resides. 
- Also, a link to the doc in the docs git repo for anyone wanting to update the doc.

### CODE REVIEW

**Comment by kmurphypolygon** [comment]
> We require contributors/corporates @kmurphypolygon to read our Contributor License Agreement, please check the [Individual CLA document](https://github.com/0xPolygonHermez/clabot-config/blob/master/Individual%20CLA%20-%20Polygon%20zkEVM.pdf)/[Corporate CLA document](https://github.com/0xPolygonHermez/clabot-config/blob/master/Corporate%20CLA%20-%20Polygon%20zkEVM.pdf)

DONE

**Comment by kmurphypolygon** [comment]
I couldn't add you as a reviewer @ARR552 please could you review?

**Comment by ARR552** [comment]
@clabot check

**Comment by ARR552** [comment]
@cla-bot check

**Comment by kmurphypolygon** [comment]
Closing as not required.

**Pull request closed without merging**
